# Generated by Django 3.0.3 on 2020-03-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
