# Generated by Django 3.0.3 on 2020-03-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_in_video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='uri',
            new_name='file',
        ),
    ]
