# Generated by Django 3.0.3 on 2020-04-01 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_in_video', '0004_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(default='user-pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
