# Generated by Django 3.0.5 on 2020-04-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_in_video', '0006_video_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='extracted_by',
            field=models.CharField(default='audio', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertexs', to='search_in_video.Word')),
            ],
        ),
    ]
