# Generated by Django 3.0.5 on 2020-04-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_in_video', '0007_auto_20200412_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertex',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='search_in_video.Word'),
        ),
    ]
