# Generated by Django 3.0.5 on 2020-04-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_in_video', '0008_auto_20200413_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
